env:
  global:
    secure: ItCwQCmiTy3s3ZUlXA+JpVSAKZYDs7FK2t4qVnBD1Dae2stEGRho7N+1oAhwnyca8Nng30hfxNT9okPZvmf39j44wbOa382PNyKP4d9iTkmR/omwlYtumuq6IbTlxTKLoQaeQEAbiAA7YYeqTscd95Ks9jC83HX1bwAOwJoznyDy2BIJRFFTjlb5vxSOxACd3Cwz7aOxmtau8b+jc3US2VCxdPfLww6IeAbXobS+aN9cvp8YVWRkUiO0e6bSwlXi5NwHyFz3oDP4KAfhtco67yGAEIbZkH+EKFnwKFx6mjD8AU4bW2qvdEcLOIjhfZWfaME7JxSarwL1yyVTeD5gPyNId0dHjbPk7knu3+w3A0rwLMxi6qsG/vEvCkujh1LQPVBvwrV3UCQYkk5BeQdAud2SoMg0E8kiOhKNchqES9kf/1jXnrLeW3Tpmu4xkjZgC0J3wF6A57rQDaxDQLdJIc86yIp/zN2tKb78uGNQxXrC/GFKA48rIiPL5hyy9f+huHEtNVFKpSVSGRidOMdXnafD8+lR/284IuL8yTSgA2YYAZbdKaM4sMqijeoVctT5PyjnQBaPFzw/WJkMpg2vOzyC4r5R5vNgqUkapwES1MVn7gyxi09LaFbcYcRU+tVhqUKnuJIWlxpxOWKCCnXEqmhZo+CcQj7vEOeg9K6Z3IA=

language: php

php:
  - 7.0

before_script:
  - composer install --prefer-dist

addons:
    code_climate:
        repo_token: ${secure}

script:
    - ./bin/phpunit

after_script:
    - CODECLIMATE_REPO_TOKEN=${secure} vendor/bin/test-reporter
